// GENERATED by tools/art/pet_art.py — do not edit.
// Shared standard palette for all 64x64 pet creature art. '.' (transparent)
// and '@' (accent placeholder) are reserved and deliberately absent.

extension PetPalette {
    public static let standard = PetPalette(colors: [
        "k": PetColor(r: 26, g: 26, b: 29, a: 255), // black outline
        "d": PetColor(r: 99, g: 99, b: 102, a: 255), // dark gray
        "e": PetColor(r: 142, g: 142, b: 147, a: 255), // mid gray
        "l": PetColor(r: 199, g: 199, b: 204, a: 255), // light gray
        "b": PetColor(r: 93, g: 64, b: 39, a: 255), // dark brown
        "m": PetColor(r: 146, g: 102, b: 57, a: 255), // mid brown
        "t": PetColor(r: 196, g: 152, b: 102, a: 255), // tan brown
        "c": PetColor(r: 243, g: 229, b: 199, a: 255), // cream
        "w": PetColor(r: 255, g: 255, b: 255, a: 255), // white
        "p": PetColor(r: 244, g: 166, b: 178, a: 255), // pink
        "n": PetColor(r: 216, g: 118, b: 135, a: 255), // rose pink
        "r": PetColor(r: 211, g: 64, b: 55, a: 255), // red
        "o": PetColor(r: 232, g: 141, b: 59, a: 255), // orange
        "y": PetColor(r: 244, g: 205, b: 80, a: 255), // yellow
        "g": PetColor(r: 58, g: 125, b: 68, a: 255), // dark green
        "h": PetColor(r: 126, g: 190, b: 101, a: 255), // light green
        "u": PetColor(r: 91, g: 141, b: 222, a: 255) // blue
    ])
}
