import ClaudeCatCore

public struct PetColor: Equatable {
    public var r: UInt8
    public var g: UInt8
    public var b: UInt8
    public var a: UInt8

    public init(r: UInt8, g: UInt8, b: UInt8, a: UInt8) {
        self.r = r
        self.g = g
        self.b = b
        self.a = a
    }
}

// Maps art characters to colors. '.' (transparent) and '@' (accent
// placeholder) are reserved by the validator and never appear in `colors`.
// The `standard` palette is generated by the Python art tool into
// Art/PetPaletteData.swift so Python stays the single source of truth.
public struct PetPalette {
    public let colors: [Character: PetColor]

    public init(colors: [Character: PetColor]) {
        self.colors = colors
    }

    // Concrete accent RGB per model family. Deliberately parallel to
    // UsageEngine.accentColors in the app layer (NSColor, menu-bar tint):
    // both encode the same per-model colors and must be kept visually in
    // sync when either changes. They stay separate because this module is
    // AppKit-free and cannot reference NSColor.
    public static func accentColor(for family: ModelFamily?) -> PetColor {
        switch family {
        case .opus:
            return PetColor(r: 230, g: 126, b: 34, a: 255)
        case .sonnet:
            return PetColor(r: 52, g: 120, b: 246, a: 255)
        case .haiku:
            return PetColor(r: 46, g: 174, b: 82, a: 255)
        case .fable:
            return PetColor(r: 155, g: 89, b: 182, a: 255)
        case .other, nil:
            return PetColor(r: 142, g: 142, b: 147, a: 255)
        }
    }
}
